// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlFpodM8OEYrNTE8v0d6Y3SL709RLPous',
    appId: '1:642287732371:web:d2f9012ff4c746a9b8ef66',
    messagingSenderId: '642287732371',
    projectId: 'fir-ogrenme-9e1d2',
    authDomain: 'fir-ogrenme-9e1d2.firebaseapp.com',
    storageBucket: 'fir-ogrenme-9e1d2.firebasestorage.app',
    measurementId: 'G-FFBX7D0HC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSB1aKgB2fnIHRHWCodRIf0pHCA788Un0',
    appId: '1:642287732371:android:8279fd6fe12eae1cb8ef66',
    messagingSenderId: '642287732371',
    projectId: 'fir-ogrenme-9e1d2',
    storageBucket: 'fir-ogrenme-9e1d2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6_9yjXi8WUCvSwaWVCSoagbIO7OkhKBQ',
    appId: '1:642287732371:ios:051cdd55f72c39cfb8ef66',
    messagingSenderId: '642287732371',
    projectId: 'fir-ogrenme-9e1d2',
    storageBucket: 'fir-ogrenme-9e1d2.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDeneme',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6_9yjXi8WUCvSwaWVCSoagbIO7OkhKBQ',
    appId: '1:642287732371:ios:051cdd55f72c39cfb8ef66',
    messagingSenderId: '642287732371',
    projectId: 'fir-ogrenme-9e1d2',
    storageBucket: 'fir-ogrenme-9e1d2.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDeneme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlFpodM8OEYrNTE8v0d6Y3SL709RLPous',
    appId: '1:642287732371:web:2267f39885839d96b8ef66',
    messagingSenderId: '642287732371',
    projectId: 'fir-ogrenme-9e1d2',
    authDomain: 'fir-ogrenme-9e1d2.firebaseapp.com',
    storageBucket: 'fir-ogrenme-9e1d2.firebasestorage.app',
    measurementId: 'G-ZWL62CWBTT',
  );
}
